import { Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import AppWrap from "./appWrap";
import PeerListener from "./peerConnection";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body className={inter.className}>
        <AppWrap>{children}</AppWrap>
      </body>
    </html>
  );
}
