--- 
  name : PRODUCTION PSYMAX APP FLOW
  on: 
    push:
      tags:    
        - 'v*.*.*'
  jobs:
    init:
      runs-on: production
      steps:
        - run: | 
            echo "### PSYMAX-Application  :date: $(date)" >> $GITHUB_STEP_SUMMARY  
    docker-down:
      runs-on: production
      needs: [init]
      steps:
        - uses: actions/checkout@v4
          with:
            ref: main
        - run: |
              export APP_TAG=${GITHUB_SHA::7}
              docker-compose down

    remove-docker-image: 
      needs: [docker-down]
      uses: RRFOORG/gitops/.github/workflows/r-remove-docker-image.yml@main
      with:
        images: "['psymax_backend','psymax_frontend']"
        runs-on: "production"
        
    docker-up:
      runs-on: production
      needs: [docker-down,remove-docker-image]
      steps:
        - uses: actions/checkout@v4
          with:
            ref: main
        - run: | 
            docker-compose up --build -d   
    done:
      needs: [docker-up]   
      runs-on: production
      steps:
        - name:
          run: |
           echo "- ### Production deployment complete:rocket: :date: $(date)" >> $GITHUB_STEP_SUMMARY