--- 
  name : STAGING PSYMAX APP FLOW
  on: 
    push:
      branches:
        - staging
  jobs:
    init:
      runs-on: staging
      steps:
        - run: | 
            echo "### PSYMAX-Application  :date: $(date)" >> $GITHUB_STEP_SUMMARY 
    eslint:
      needs: [init]
      uses: RRFOORG/gitops/.github/workflows/r-eslint.yml@main
      with:
        directory: "['backend','frontend']"
  
    docker-down:
      runs-on: staging
      needs: [init,eslint]
      steps:
        - uses: actions/checkout@v4
          with:
            ref: staging
        - run: |
              export APP_TAG=${GITHUB_SHA::7}
              docker-compose down

    remove-docker-image: 
      needs: [docker-down,eslint]
      uses: RRFOORG/gitops/.github/workflows/r-remove-docker-image.yml@main
      with:
        images: "['psymax_backend','psymax_frontend']"
        runs-on: "staging"
        
    docker-up:
      runs-on: staging
      needs: [docker-down,remove-docker-image]
      steps:
        - uses: actions/checkout@v4
          with:
            ref: staging
        - run: |
            export APP_TAG=${GITHUB_SHA::7}
            docker-compose up --build -d
    sec-vul:  
      needs: [docker-up]
      if: |
        github.event_name == 'push' &&
        contains(github.ref, 'refs/heads/staging') 
      strategy:
        fail-fast: false
        matrix:
          include:
            - directory: backend
              port: 4000
            - directory: frontend
              port: 3000
      uses: RRFOORG/gitops/.github/workflows/r-security-vulnerability.yml@main
      with:
        directory: ${{matrix.directory}}
        port: ${{matrix.port}}
        image_name: "psymax"
        runs-on: "staging"
        
    done:
      needs: [sec-vul]   
      runs-on: staging
      steps:
        - name:
          run: |
           echo "- ### Staging flow done. :rocket: :date: $(date)" >> $GITHUB_STEP_SUMMARY